// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: rpc/basicCrudService/service.proto

package basicCrudService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Size of a Hat, in inches.
type ResponseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // must be > 0
}

func (x *ResponseMsg) Reset() {
	*x = ResponseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_basicCrudService_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMsg) ProtoMessage() {}

func (x *ResponseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_basicCrudService_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMsg.ProtoReflect.Descriptor instead.
func (*ResponseMsg) Descriptor() ([]byte, []int) {
	return file_rpc_basicCrudService_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseMsg) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// A Hat is a piece of headwear made by a Haberdasher.
type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"` // anything but "invisible"
	Body  string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`   // i.e. "bowler"
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_basicCrudService_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_basicCrudService_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_rpc_basicCrudService_service_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type NullVal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullVal) Reset() {
	*x = NullVal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_basicCrudService_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullVal) ProtoMessage() {}

func (x *NullVal) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_basicCrudService_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullVal.ProtoReflect.Descriptor instead.
func (*NullVal) Descriptor() ([]byte, []int) {
	return file_rpc_basicCrudService_service_proto_rawDescGZIP(), []int{2}
}

type Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Items) Reset() {
	*x = Items{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_basicCrudService_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_basicCrudService_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_rpc_basicCrudService_service_proto_rawDescGZIP(), []int{3}
}

func (x *Items) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_rpc_basicCrudService_service_proto protoreflect.FileDescriptor

var file_rpc_basicCrudService_service_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x29, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x30, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x22, 0x09, 0x0a, 0x07, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x22, 0x35,
	0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72,
	0x75, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xa4, 0x02, 0x0a, 0x10, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43,
	0x72, 0x75, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x1d, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x44, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x19, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x43, 0x72, 0x75, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x75, 0x6c, 0x6c,
	0x56, 0x61, 0x6c, 0x1a, 0x1d, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75, 0x64, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x73, 0x67, 0x12, 0x43, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x1d, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x43, 0x72, 0x75, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x43, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x1d, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x42, 0x16, 0x5a, 0x14,
	0x72, 0x70, 0x63, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x43, 0x72, 0x75, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_basicCrudService_service_proto_rawDescOnce sync.Once
	file_rpc_basicCrudService_service_proto_rawDescData = file_rpc_basicCrudService_service_proto_rawDesc
)

func file_rpc_basicCrudService_service_proto_rawDescGZIP() []byte {
	file_rpc_basicCrudService_service_proto_rawDescOnce.Do(func() {
		file_rpc_basicCrudService_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_basicCrudService_service_proto_rawDescData)
	})
	return file_rpc_basicCrudService_service_proto_rawDescData
}

var file_rpc_basicCrudService_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_basicCrudService_service_proto_goTypes = []interface{}{
	(*ResponseMsg)(nil), // 0: basicCrudService.ResponseMsg
	(*Item)(nil),        // 1: basicCrudService.Item
	(*NullVal)(nil),     // 2: basicCrudService.NullVal
	(*Items)(nil),       // 3: basicCrudService.Items
}
var file_rpc_basicCrudService_service_proto_depIdxs = []int32{
	1, // 0: basicCrudService.Items.items:type_name -> basicCrudService.Item
	1, // 1: basicCrudService.basicCrudService.AddItem:input_type -> basicCrudService.Item
	2, // 2: basicCrudService.basicCrudService.GetItems:input_type -> basicCrudService.NullVal
	1, // 3: basicCrudService.basicCrudService.UpdateItem:input_type -> basicCrudService.Item
	1, // 4: basicCrudService.basicCrudService.DeleteItem:input_type -> basicCrudService.Item
	0, // 5: basicCrudService.basicCrudService.AddItem:output_type -> basicCrudService.ResponseMsg
	0, // 6: basicCrudService.basicCrudService.GetItems:output_type -> basicCrudService.ResponseMsg
	0, // 7: basicCrudService.basicCrudService.UpdateItem:output_type -> basicCrudService.ResponseMsg
	0, // 8: basicCrudService.basicCrudService.DeleteItem:output_type -> basicCrudService.ResponseMsg
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_basicCrudService_service_proto_init() }
func file_rpc_basicCrudService_service_proto_init() {
	if File_rpc_basicCrudService_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_basicCrudService_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_basicCrudService_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_basicCrudService_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullVal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_basicCrudService_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Items); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_basicCrudService_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_basicCrudService_service_proto_goTypes,
		DependencyIndexes: file_rpc_basicCrudService_service_proto_depIdxs,
		MessageInfos:      file_rpc_basicCrudService_service_proto_msgTypes,
	}.Build()
	File_rpc_basicCrudService_service_proto = out.File
	file_rpc_basicCrudService_service_proto_rawDesc = nil
	file_rpc_basicCrudService_service_proto_goTypes = nil
	file_rpc_basicCrudService_service_proto_depIdxs = nil
}
